version: '3.8'
services:
  frontend:
    build: ./frontend
    ports: ["5000:5000"]
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    depends_on: [rabbitmq, db]

  worker:
    build: ./worker
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    depends_on: [rabbitmq]

  rabbitmq:
    image: rabbitmq:3-management
    ports: ["15672:15672"]
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: lab123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  uploads:
  results:
