version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    environment: {ZOOKEEPER_CLIENT_PORT: 2181}

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on: [zookeeper]
    ports: ["9092:9092"]
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  init-kafka:
    image: confluentinc/cp-kafka:7.3.2
    depends_on: [kafka]
    command: >
      bash -c "cub kafka-ready -b kafka:9092 1 30 &&
               kafka-topics --bootstrap-server kafka:9092 
                            --create --topic tasks 
                            --partitions 6 --replication-factor 1"

  producer:
    build: ./producer
    depends_on: [init-kafka]

  worker:
    build: ./worker
    depends_on: [kafka]
